# Generated by Django 5.1.3 on 2024-11-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.TextField(help_text='Hero section text')),
                ('hero_image', models.ImageField(help_text='Hero section image', upload_to='hero_section/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload slider image', upload_to='home_slider/')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_logo', models.ImageField(blank=True, help_text='Upload primary logo', null=True, upload_to='logos/')),
                ('secondary_logo', models.ImageField(blank=True, help_text='Upload secondary logo', null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=100)),
                ('description', models.TextField(help_text='Service description')),
                ('image', models.ImageField(help_text='Service image', upload_to='services/')),
            ],
        ),
    ]
