# Generated by Django 5.1.3 on 2024-11-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(help_text='Upload slider image 1', upload_to='image_slider/')),
                ('image2', models.ImageField(help_text='Upload slider image 2', upload_to='image_slider/')),
                ('image3', models.ImageField(help_text='Upload slider image 3', upload_to='image_slider/')),
                ('image4', models.ImageField(help_text='Upload slider image 4', upload_to='image_slider/')),
                ('image5', models.ImageField(help_text='Upload slider image 5', upload_to='image_slider/')),
            ],
        ),
        migrations.DeleteModel(
            name='HomeSliderImage',
        ),
    ]
