# Generated by Django 5.1.3 on 2024-11-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0002_imagesliderimage_delete_homesliderimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageSliderImage',
            new_name='ImageSlider',
        ),
    ]
