# Generated by Django 5.1.3 on 2024-11-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0003_rename_imagesliderimage_imageslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSlider',
        ),
    ]
