# Generated by Django 5.1.3 on 2024-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0005_imageslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section image', null=True, upload_to='hero_section/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='hero_text',
            field=models.TextField(blank=True, help_text='Hero section text', null=True),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='image1',
            field=models.ImageField(blank=True, help_text='Upload slider image 1', null=True, upload_to='image_slider/'),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='image2',
            field=models.ImageField(blank=True, help_text='Upload slider image 2', null=True, upload_to='image_slider/'),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='image3',
            field=models.ImageField(blank=True, help_text='Upload slider image 3', null=True, upload_to='image_slider/'),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='image4',
            field=models.ImageField(blank=True, help_text='Upload slider image 4', null=True, upload_to='image_slider/'),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='image5',
            field=models.ImageField(blank=True, help_text='Upload slider image 5', null=True, upload_to='image_slider/'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='description',
            field=models.TextField(blank=True, help_text='Service description', null=True),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='title',
            field=models.CharField(blank=True, help_text='Service title', max_length=100, null=True),
        ),
    ]
