# Generated by Django 5.1.3 on 2024-11-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0008_rename_description_servicesection_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesection',
            old_name='description1',
            new_name='service_description1',
        ),
        migrations.RenameField(
            model_name='servicesection',
            old_name='description2',
            new_name='service_description2',
        ),
        migrations.RenameField(
            model_name='servicesection',
            old_name='description3',
            new_name='service_description3',
        ),
        migrations.RenameField(
            model_name='servicesection',
            old_name='image1',
            new_name='service_image1',
        ),
        migrations.RenameField(
            model_name='servicesection',
            old_name='image2',
            new_name='service_image2',
        ),
        migrations.RenameField(
            model_name='servicesection',
            old_name='image3',
            new_name='service_image3',
        ),
        migrations.RenameField(
            model_name='servicesection',
            old_name='title1',
            new_name='service_title1',
        ),
        migrations.RenameField(
            model_name='servicesection',
            old_name='title2',
            new_name='service_title2',
        ),
        migrations.RenameField(
            model_name='servicesection',
            old_name='title3',
            new_name='service_title3',
        ),
    ]
