# Generated by Django 5.1.3 on 2024-11-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0009_rename_description1_servicesection_service_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ceo', models.CharField(blank=True, help_text='Name CEO', max_length=100, null=True)),
                ('image_ceo', models.ImageField(blank=True, help_text='business structure image', null=True, upload_to='business_structure/')),
                ('name_coo', models.CharField(blank=True, help_text='Name COO', max_length=100, null=True)),
                ('image_coo', models.ImageField(blank=True, help_text='business structure image', null=True, upload_to='business_structure/')),
                ('name_cfo', models.CharField(blank=True, help_text='Name CFO', max_length=100, null=True)),
                ('image_cfo', models.ImageField(blank=True, help_text='business structure image', null=True, upload_to='business_structure/')),
                ('name_cto', models.CharField(blank=True, help_text='Name CTO', max_length=100, null=True)),
                ('image_cto', models.ImageField(blank=True, help_text='business structure image', null=True, upload_to='business_structure/')),
                ('name_cmo', models.CharField(blank=True, help_text='Name CMO', max_length=100, null=True)),
                ('image_cmo', models.ImageField(blank=True, help_text='business structure image', null=True, upload_to='business_structure/')),
            ],
        ),
        migrations.CreateModel(
            name='PhilosphySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philosophy_image', models.ImageField(blank=True, help_text='Philosophy section image', null=True, upload_to='philosophy/')),
                ('philosphy_text', models.TextField(blank=True, help_text='Philosphy section text', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_title1', models.CharField(blank=True, help_text='Solutions Title', max_length=100, null=True)),
                ('solution_description1', models.TextField(blank=True, help_text='Solutions Description', null=True)),
                ('solution_title2', models.CharField(blank=True, help_text='Solutions Title', max_length=100, null=True)),
                ('solution_description2', models.TextField(blank=True, help_text='Solutions Description', null=True)),
                ('solution_title3', models.CharField(blank=True, help_text='Solutions Title', max_length=100, null=True)),
                ('solution_description3', models.TextField(blank=True, help_text='Solutions Description', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisionMissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_text', models.TextField(blank=True, help_text='Vision section text', null=True)),
                ('mision_text', models.TextField(blank=True, help_text='Mision section text', null=True)),
            ],
        ),
    ]
