# Generated by Django 5.1.3 on 2024-11-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0010_businessstructure_philosphysection_solutionssection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='philosphysection',
            old_name='philosphy_text',
            new_name='philosophy_text',
        ),
    ]
