# Generated by Django 5.1.3 on 2024-11-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0011_rename_philosphy_text_philosphysection_philosophy_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visionmissionsection',
            old_name='mision_text',
            new_name='mission_text',
        ),
    ]
