# Generated by Django 5.1.3 on 2024-11-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0012_rename_mision_text_visionmissionsection_mission_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Phone Number', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=100, null=True)),
                ('address', models.TextField(blank=True, help_text='Address', null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Whatsapp', max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram', max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(blank=True, help_text='Longitude', max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, help_text='Latitude', max_length=100, null=True)),
            ],
        ),
    ]
