# Generated by Django 5.1.3 on 2024-11-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0015_alter_activities_status_alter_blogs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('health', 'Health'), ('science', 'Science'), ('services', 'Services'), ('news', 'News'), ('diseases', 'Diseases'), ('events', 'Events'), ('education', 'Education'), ('lifestyle', 'LifeStyle'), ('medicine', 'Medicine')], default='health', max_length=100),
        ),
    ]
