# Generated by Django 5.1.3 on 2024-11-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NusaHealthApp', '0017_alter_blogs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Sports', 'Sports'), ('Health', 'Health'), ('Science', 'Science'), ('Services', 'Services'), ('News', 'News'), ('Diseases', 'Diseases'), ('Events', 'Events'), ('Education', 'Education'), ('LifeStyle', 'LifeStyle'), ('Medicine', 'Medicine')], default='health', max_length=100),
        ),
    ]
